# Generated by Django 3.1.2 on 2020-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201214_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='listen',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=('Y', 'Yes'), max_length=1),
        ),
    ]
