# Generated by Django 3.1.2 on 2020-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201214_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vibe', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listening',
            name='date',
            field=models.DateField(verbose_name='listening date'),
        ),
        migrations.AddField(
            model_name='banger',
            name='playlists',
            field=models.ManyToManyField(to='main_app.Playlist'),
        ),
    ]
